language: node_js
node_js:
  - "8"
cache:
  directories:
    - node_modules
env:
  global:
    - CC_TEST_REPORTER_ID=6261ba4f6e5890c37688f390015831023481b8bedf53a2fec3e23695b6223513
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
install:
  - npm install
  - npm install -g jest
script:
  - npm test
  - npm run build
